// Firebase Configuration for Hackly
// This file will be dynamically generated during deployment with GitHub Actions
// The configuration will be injected by the GitHub Actions workflow

// This file should be generated by GitHub Actions and contain the Firebase config
// If you see this message, make sure GitHub Actions is properly configured
if (typeof window !== 'undefined' && !window.__FIREBASE_CONFIG__) {
  console.error('❌ Firebase configuration not found. Make sure GitHub Actions is properly configured to inject window.__FIREBASE_CONFIG__');
}
