name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: |
          echo "Starting build process..."
          
          # Create dist directory with the correct structure
          mkdir -p dist/features/garage-interface/frontend/scripts
          echo "Created dist directory structure"
          
          # Copy frontend files maintaining the structure
          cp -r features/garage-interface/frontend/* dist/features/garage-interface/frontend/
          echo "Copied frontend files"
          
          # Create config.js with proper exports
          echo "Creating config.js..."
          cat > dist/features/garage-interface/frontend/scripts/config.js << EOL
          export const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
          };
          EOL
          
          # Verify config.js was created and has content
          if [ ! -f dist/features/garage-interface/frontend/scripts/config.js ]; then
            echo "Error: config.js was not created"
            exit 1
          fi
          
          # Verify the structure of the dist directory
          echo "Verifying dist directory structure..."
          ls -R dist/features/garage-interface/frontend/
          
          # Verify config.js content (without exposing secrets)
          echo "Verifying config.js structure..."
          if ! grep -q "export const firebaseConfig" dist/features/garage-interface/frontend/scripts/config.js; then
            echo "Error: config.js does not contain the expected export"
            exit 1
          fi
          
          # Create a copy of config.js in the root scripts directory for testing
          cp dist/features/garage-interface/frontend/scripts/config.js dist/features/garage-interface/frontend/scripts/config.js.bak
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          
      - name: Verify Deployment
        run: |
          echo "Deployment completed. Please check your GitHub Pages URL."
          echo "Note: It may take a few minutes for changes to be visible."
          echo "You can check the deployment status at: https://github.com/${{ github.repository }}/deployments" 